---

- name: Load balancer setup
  hosts: loadbalancers
  remote_user: root
  roles:
    - common
    - loadbalancer

- name: Primary load balancer keepalived config
  hosts: primary_lb
  remote_user: root
  roles:
    - keepalive
    
- name: Backup load balancer keepalive config
  hosts: backup_lb
  remote_user: root
  roles:
    - keepalive_backup

- name: Web server setup
  hosts: webservers
  remote_user: root
  roles:
    - common
    - web
