---
- name: Load balancer setup
  hosts: loadbalancers
  remote_user: root
  roles:
    - common
    - loadbalancer

- name: Web server setup
  hosts: webservers
  remote_user: root
  roles:
    - common
    - web
 
- name: Glusterfs setup
  hosts: storage
  remote_user: root
  roles:
    - common
    - glusterfs

- name: freeipa client install
  hosts: freeipatest
  remote_user: root
  roles:
    - common
    - freeipa

- name: postgresql db install
  hosts: databases
  remote_user: root
    roles:
    - common
    - database
