---

- name: Load balancer setup
  hosts: loadbalancers
  remote_user: root
  roles:
    - common
    - loadbalancer

- name: Glusterfs setup
  hosts: storage
  remote_user: root
  roles:
    - common
    - glusterfs

- name: Web server setup
  hosts: webservers
  remote_user: root
  roles:
    - common
    - web
