---
# load balancer configuration
- name: install nginx
  package: name=nginx state=present update_cache=yes

- name: start nginx
  service: name=nginx state=started enabled=yes

- name: configure the load balancer
  template: 
    src="{{ nginx_config_path }}/backend.conf"
    dest=/etc/nginx/conf.d/
    mode=0644
  notify: restart nginx
  
- name: remove default nginx config file
  file: path=/etc/nginx/nginx.conf state=absent
  
- name: deploy the new nginx.conf file
  template:
    src="{{ nginx_config_path }}/nginx.conf"
    dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: install keepalived
  package: name=keepalived state=present update_cache=yes
  
- name: copy over hte keepalived config for master server
  vars:
    servers:
      "lb1.internal.virtnet": "lb1"
      "lb2.internal.virtnet": "lb2"
  template:
    src: "{{ keepalived_config_path }}/keepalived.conf"
    dest: "{{ keepalived_dest_path }}/keepalived.conf"
    when: servers[ansible_hostname] == "lb1"
    notify:
    - restart keepalived
      
- hosts: lb2.internal.virtnet
  tasks:
    - name: copy over the keepalived config for secondary server
      template:
        src: "{{ keepalived_config_path }}/keepalived.conf2"
        dest: "{{ keepalived_dest_path }}/keepalived.conf"
      notify:
      - restart keepalived
      
- name: start and enable keepalived
  service: name=keepalived state=started enabled=yes
  notify:
  - restart nginx
  - restart keepalived
