---
# load balancer configuration
- name: install nginx
  package: name=nginx state=present update_cache=yes

- name: start nginx
  service: name=nginx state=started enabled=yes

- name: configure the load balancer
  template: 
    src="{{ nginx_config_path }}/backend.conf"
    dest=/etc/nginx/conf.d/
    mode=0644
  notify: restart nginx
  
- name: remove default nginx config file
  file: path=/etc/nginx/nginx.conf state=absent
  
- name: deploy the new nginx.conf file
  template:
    src="{{ nginx_config_path }}/nginx.conf"
    dest=/etc/nginx/nginx.conf
  notify: restart nginx

# keepalived install

-	name: install keepalived
	package: keepalived state=present update_cache=yes

-	name: start keepalived
	service: name=keepalived state=started enabled=yes

-	hosts: lb1.internal.virtnet
	tasks:
	- name: copy over the keepalived config for master server
		template:
			src: "{{ keepalived_config_path }}/keepalived.conf"
			dest: "{{ keepalived_dest_path }}/keepalived.conf"
		notify:
		-	restart keepalived

-	hosts: lb2.internal.virtnet
	tasks:
		- name: copy over keepalived config for secondary server
		template:
			src: "{{ keepalived_config_path }}/keepalived2.conf"
			dest: "{{ keepalived_dest_path }}/keepalived.conf"
		notify:
		-	restart keepalived
