---
# load balancer configuration
- name: install nginx
  package: name=nginx state=present update_cache=yes

- name: start nginx
  service: name=nginx state=started enabled=yes

- name: configure the load balancer
  template: 
    src=/home/louis/code/ansible/playbooks/app/webapp/roles/loadbalancer/templates/backend.conf
    dest=/etc/nginx/conf.d/
    mode=0644
  notify: restart nginx
