---
# load balancer configuration
- name: install nginx
  package: name=nginx state=present update_cache=yes

- name: start nginx
  service: name=nginx state=started enabled=yes

- name: configure the load balancer
  template: 
    src=/home/louis/code/ansible/playbooks/app/webapp/roles/loadbalancer/templates/nginx.conf.j2
    dest=/etc/nginx/sites-available/test.internal.virtnet.conf
    mode=0644
  notify: restart nginx

- name: delete old link
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

- name: activate test site
  file: src=/etc/nginx/sites-available/test.internal.virtnet.conf dest=/etc/nginx/sites-enabled/test.internal.virtnet.conf state=link
  notify: restart nginx
