---
# load balancer configuration
- name: install nginx
  package: name=nginx state=present update_cache=yes

- name: start nginx
  service: name=nginx state=started enabled=yes

- name: configure the load balancer
  template: 
    src="{{ nginx_config_path }}/backend.conf"
    dest=/etc/nginx/conf.d/
    mode=0644
  notify: restart nginx
  
- name: remove default nginx config file
  file: path=/etc/nginx/nginx.conf state=absent
  
- name: deploy the new nginx.conf file
  template:
    src="{{ nginx_config_path }}/nginx.conf"
    dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: install keepalived
  package: name=keepalived state=present update_cache=yes

- name: remove the default keepalived config file
  file: path=/etc/keepalived/keepalived.conf state=absent
  
- name: copy over the keepalived config
  copy:
    src="{{ keepalived_config_path }}/lb_config.j2"
    dest=/etc/keepalived/keepalived.conf
  notify:
    - restart keepalived
   
- name: start and enable keepalived
  service: name=keepalived state=started enabled=yes
  notify:
    - restart nginx
    - restart keepalived
