---
# load balancer configuration
- name: install nginx
  package: name=nginx state=present update_cache=yes

- name: start nginx
  service: name=nginx state=started enabled=yes

- name: delete old link
  file: path=/etc/nginx/nginx.conf state=absent
  notify: restart nginx

- name: configure the load balancer
  template: 
    src=/home/louis/code/ansible/playbooks/app/webapp/roles/loadbalancer/templates/nginx.conf
    dest=/etc/nginx/nginx.conf
    mode=0644
  notify: restart nginx
