---
# load balancer configuration
- name: install nginx
  package: name=nginx state=present update_cache=yes

- name: start nginx
  service: name=nginx state=started enabled=yes

- name: configure the load balancer
  template: 
    src="{{ nginx_config_path }}/backend.conf"
    dest=/etc/nginx/conf.d/
    mode=0644
  notify: restart nginx
  
- name: remove default nginx config file
  file: path=/etc/nginx/nginx.conf state=absent
  
- name: deploy the new nginx.conf file
  template:
    src="{{ nginx_config_path }}/nginx.conf"
    dest=/etc/nginx/nginx.conf
  notify: restart nginx
