---

- name: Install pgbouncer
  get_url: https://download.postgresql.org/pub/repos/yum/9.3/redhat/rhel-6-x86_64/pgdg-ami201503-93-9.3-3.noarch.rpm
  dest: /etc/yum.repos.d
  
- name: start and enable pgbouncer
  service: name=pgbouncer state=started enabled=yes
