---

- name: create directory for pgbouncer
  file:
    path: /pgbouncer-1.8.1
    state: directory
    mode: 0755
  
- name: download pgbouncer source
  unarchive:
    src: https://pgbouncer.github.io/downloads/files/1.8.1/pgbouncer-1.8.1.tar.gz
    dest: /pgbouncer-1.8.1
    remote_src: yes

- name: download devel packages
  package: name={{ item }} state=present
  with_items:
    - 
