---

- name: Add the PostgreSQL 9.6 repo to sources.list.d
  apt_repository: 
    repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
    state: present
    
- name: Import the PostgreSQL signing key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  
- name: Update the repository
  apt:
    update_cache: yes  
  
- name: Install the PostgreSQL 9.6 packages
  package: name={{ item }} state=present
  with_items:
    - postgresql-9.6
    - postgresql-contrib-9.6
    - python-psycopg2
    
- name: In order to setup streaming replication there needs to be an archive directory
  file:
    path: "{{ pg_archive_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700

- name: Create Database user pgpool
  become: yes
  become_user: postgres
  postgresql_user:
    db: postgres
    name: pgpool
    password: "{{ pg_db_pass }}"
    priv: ALL
    
- name: Create Database user repl
  become: yes
  become_user: postgres
  postgresql_user:
    db: postgres
    name: repl
    password: " {{ pg_db_pass }}"
    role_attr_flags: REPLICATION
    priv: all

- name: remove the old postgresql.conf file
  file: path=/etc/postgresql/9.6/main/postgresql.conf state=absent
  
- name: remove the old pg_hba.conf file
  file: path=/etc/postgresql/9.6/main/pg_hba.conf state=absent
  
- name: copy over the postgresql.conf file
  template: 
    src: "templates/postgresql.conf" 
    dest: "/etc/postgresql/9.6/main/postgresql.conf"
  notify:
    - restart postgresql
    
- name: set proper permissions on the config file
  file:
    path: /etc/postgresql/9.6/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0644

- name: copy over the pg_hba.conf file
  template:
    src: "templates/pg_hba.conf"
    dest: "/etc/postgresql/9.6/main/pg_hba.conf
  notify:
    - restart postgresql
  
- name: set proper permission on the pg_hba.conf file
  file:
    path: /etc/postgresql/9.6/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0644
    
- name: copy over the primary .pgpass file
  template:
    src: "templates/pgpass_primary"
    dest: "/var/lib/postgresql/.pgpass"
  when: inventory_hostname == "{{ primary_db }}"
  
- name: copy over the secondary .pgpass file
  template:
    src: "templates/pgpass_secondary"
    dest: "/var/lib/postgresql/.pgpass"
  when: inventory_hostname == "{{ secondary_db }}"
  
- name: set permissions on the .pgpass file
  file:
    path: /var/lib/postgresql/.pgpass
    owner: postgres
    group: postgres
    mode: 0600
    
- name: enable postgresql on boot
  service: name=postgresql state=started enabled=yes
