---

- name: Add the PostgreSQL 9.6 repo to sources.list.d
  command: echo 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main' | tee /etc/apt/sources.list.d/postgresql.list
  
- name: Import the PostgreSQL signing key to the system.
  command: wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | sudo apt-key add -
  
- name: Update the repository
  command: apt-get update
  
- name: Install the PostgreSQL 9.6 packages
  package: name={{ item }} state=present
  with_items:
    - postgresql-9.6
    - postgresql-contrib-9.6
    
- name: In order to setup streaming replication there needs to be an archive directory
  file:
    path: "{{ pg_archive_dir }}"
    state: directory
    mode: 0755
