---

- name: download postgresql repo
  get_url:
    url: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm
    dest: /etc/yum.repos.d/
    mode: 0644

- name: install the server packages
  package: name={{ item }} state=installed
  with_items:
    - postgresql96
    - postgresql96-server
    - postgresql96-libs
    - postgresql96-contrib
    - python-psycopg2
    - libevent-devel
    
- name: Initialize the database
  command: /usr/pgsql-9.6/bin/postgresql96-setup initdb

- name: start the postgresql service
  service: name=postgresql-9.6.service state=started enabled=yes
