---

- name: Add the PostgreSQL 9.6 repo to sources.list.d
  apt_repository: 
    repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
    state: present
    
- name: Import the PostgreSQL signing key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  
- name: Update the repository
  apt:
    update_cache: yes  
  
- name: Install the PostgreSQL 9.6 packages
  package: name={{ item }} state=present
  with_items:
    - postgresql-9.6
    - postgresql-contrib-9.6
    - psycopg2
    
- name: In order to setup streaming replication there needs to be an archive directory
  file:
    path: "{{ pg_archive_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700

- name: Create Database user pgpool
  become: yes
  become_user: postgres
  postgresql_user:
    db: postgres
    name: pgpool
    password: "{{ pg_db_pass }}"
    priv: ALL
    
- name: Create Database user repl
  become: yes
  become_user: postgres
  postgresql_user:
    db: replication
    name: repl
    password: " {{ pg_db_pass }}"
    priv: all
