---

- name: download postgresql repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm
    state: present

- name: set repo file permissions
  file: owner=root group=root mode=0644
        path=/etc/yum.repos.d/pgdg-96-centos.repo

- name: install the server packages
  package: name={{ item }} state=installed
  with_items:
    - postgresql96
    - postgresql96-server
    - postgresql96-libs
    - postgresql96-contrib
    - python-psycopg2
    - libevent-devel

- name: start the postgresql service
  service: name=postgresql-9.6.service state=started enabled=yes
