---
- name: install glusterfs
  package: name={{ item }} state=present
  with_items:
    - glusterfs-api
    - glusterfs
    - glusterfs-cli
    - glusterfs-fuse
    - glusterfs-libs
    - centos-release-gluster
    - glusterfs-server
    - xfsprogs

- name: create the partition
  parted:
    device: /dev/sdb
    number: 1
    state: present
        
- name: create xfs file system on /dev/sdb
  filesystem:
    fstype: xfs
    dev: /dev/sdb1
    opts: -i size=512

- name: create the mount directory
  file: path=/data/gluster state=directory mode=0776

- name: mount the new partition
  mount:
    path: /data/gluster
    src: /dev/sdb1
    fstype: xfs
    opts: defaults,0,0
    state: present

- name: Create brick directory
  file: path=/data/gluster/gv0 state=directory mode=0776
    
#- name: Ensure Gluster brick and mount directories exist
  #file: "path={{ item }} state=directory mode=0776"
  #with_items:
    #- "{{ gluster_brick_dir }}"
    #- "{{ gluster_mount_dir }}"

- name: Configure gluster volume
  gluster_volume:
    state: present
    name: www-data
    brick: /data/gluster/gv0
    replicas: 2
    cluster: "{{ groups.storage | join(',') }}"
    host: "{{ inventory_hostname }}"
    force: yes
  run_once: true
  
# name: create the gluster volume
 # raw: gluster volume create gv0 replica 2 gfs1.internal.virtnet:/data/gluster/gv0 gfs2.internal.virtnet:/data/gluster/gv0
  #args:
   # executable: /bin/bash
    
#- name: start the volume
 # raw: gluster volume start gv0
  #args:
   # executable: /bin/bash
    
- name: Ensure gluster volume is mounted
  mount: 
    name: www-data
    src: "{{ groups.storage[0] }}:/data/gluster/gv0"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
