---
- name: install glusterfs
  package: name={{ item }} state=present
  with_items:
    - glusterfs-api
    - glusterfs
    - glusterfs-cli
    - glusterfs-fuse
    - glusterfs-libs
    - centos-release-gluster
    - glusterfs-server
    - xfsprogs

- name: create the partition
  parted:
    device: /dev/sdb
    number: 1
    state: present
    
- name: create the file system
  filesystem:
    fstype: xfs
    dev: /dev/sdb1
    opts: -i size=512

- name: make the directory for the bricks
  file:
    path: /data/glusterfs/var-www/brick01
    state: directory
    mode: 0755

- name: mount the device on the directory
  mount:
    path: /data/glusterfs/var-www/brick01
    fstype: xfs
    src: /dev/sdb1
    state: mounted

- name: Ensure glusterfs is running
  service: name=glusterd state=started enabled=yes
  
- name: Creater glusterfs volume
  gluster_volume:
    state: present
    name: data-www
    bricks: /data/glusterfs/var-www/brick01/brick
    cluster:
      - gluster1.internal.virtnet
      - gluster2.internal.virtnet
    run_once: true
    
- name: start gluster volume
  gluster_volume:
    name=data-www
    state=started
    
