---
- name: install glusterfs
  package: name={{ item }} state=present
  with_items:
    - glusterfs-api
    - glusterfs
    - glusterfs-cli
    - glusterfs-fuse
    - glusterfs-libs
    - centos-release-gluster
    - glusterfs-server
    - xfsprogs

- name: create the partition
  parted:
    device: /dev/sdb
    number: 1
    state: present
    
- name: create the file system
  filesystem:
    fstype: xfs
    dev: /dev/sdb1
    opts: -i size=512
