---
# Install and configure Apache webserver
- name: WEBSERVER | Install Apache webserver
  package: name=httpd state=present update_cache=yes

- name: Apache Webserver
  service: name=httpd state=started enabled=yes

- name: Delete current index.html
  file: path=/var/www/html/index.html state=absent
  notify: restart httpd

- name: copy over the index.html
  template: 
    src=/home/louis/code/ansible/playbooks/app/webapp/roles/web/template/index.html 
    dest=/var/www/html/index.html
  notify: restart httpd
  
- name: install glusterfs client
  package: name=glusterfs-client state=present
  
- name: create directory to mount glusterfs file system
  file:
    path=/data/var-www
    state=directory
    mode=0755

- name: mount the glusterfs file system
  mount:
    path=/data/var-www
    src=gluster1.internal.virtnet:/www-data
    fstype=glusterfs
    opts=defaults,_netdev,fetch-attempts=5
    state=mounted    
